// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5LZ-JFNpeWgAkTFsXJSLTJYTMMJ1PFb0',
    appId: '1:268745094547:web:f45eea59a079d02a396466',
    messagingSenderId: '268745094547',
    projectId: 'jasmine-store-50a79',
    authDomain: 'jasmine-store-50a79.firebaseapp.com',
    storageBucket: 'jasmine-store-50a79.appspot.com',
    measurementId: 'G-W882LX9G6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVez8gdmfeqwlOS7qUultifdX9peuiqM0',
    appId: '1:268745094547:android:523807fda0a4dfc4396466',
    messagingSenderId: '268745094547',
    projectId: 'jasmine-store-50a79',
    storageBucket: 'jasmine-store-50a79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBXS-GInZpU5pIQS1Wq9EGPujsI6AH4-Q',
    appId: '1:268745094547:ios:d2a259096423ed30396466',
    messagingSenderId: '268745094547',
    projectId: 'jasmine-store-50a79',
    storageBucket: 'jasmine-store-50a79.appspot.com',
    iosClientId: '268745094547-aaeo0dpmr0fdsjbcqva4jniig3c07qin.apps.googleusercontent.com',
    iosBundleId: 'com.example.jasmineApp',
  );
}
